version: 0.0
os: linux

files:
  - source: /
    destination: /opt/tailo
permissions:
  - object: /opt/tailo/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 60
      runas: root

  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root