spring:
  application:
    name: Tailo
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB
      max-request-size: 30MB
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_NUMBER}
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}


  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL}

    chat:
      exchange: ${CHAT_EXCHANGE}
      queue: ${CHAT_QUEUE}
      routing-key: ${CHAT_ROUTING}

    notification:
      exchange: ${NC_EXCHANGE}
      routing-key: ${NC_ROUTING}
      queue: ${NC_QUEUE}



## Swagger
springdoc:
  swagger-ui:
    ## custom http://localhost:8080/swagger-api-index.html
    ## default http://localhost:8080/swagger-ui/index.html
    path: /swagger-api-index.html
    operations-sorter: method
    tags-sorter: alpha
  #  api-docs:
  #    ## default http://localhost:8080/api-docs
  #    path: /api-docs
  ## endpoint 노출
  show-actuator: true
  disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  ## API로 시작하는 URL만
  paths-to-match:
    - /api/**

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
