spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jwt:
    issuer: JWT_ISSUER
    secret: JWT_SECRET
    accessTokenExpirationTime: 3600000
    refreshTokenExpirationTime: 1209600000
  data:
    redis:
      host: localhost
      port: 6378
      password: test
      database: 0

cloudinary:
  cloud_name: CLOUDINARY_CLOUD_NAME
  api_key: CLOUDINARY_KEY
  api_secret: CLOUDINARY_API_SECRET